# Online Dataset
url_dataset: 'http://vision.stanford.edu/aditya86/ImageNetDogs/images.tar'
url_list: 'http://vision.stanford.edu/aditya86/ImageNetDogs/lists.tar'
compressed_data_name: 'images.tar'
compressed_list_name: 'lists.tar'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_images: 'Images'
data_dir_list: 'dataset\List'
model_dir: 'checkpoints'
label_id_json: 'labels.json'

# Data files
train_mat_file: 'train_list.mat'
test_mat_file: 'test_list.mat'

training_data: 'training.txt'
validation_data: 'validation.txt'
test_data: 'test.txt'

# Data configuration
shuffle: True
image_shape: [224, 224, 3]

# Parameters that may affect training
batch_size: 10
learning_rate: 0.001
max_steps: 50000
width_multiplier: 1
depth_multiplier: 1
num_classes: 10
dropout_rate: 0.5
regularization_rate: 0.001
tiny_model: True
num_epochs: 45
class_mode: 'other'
loss: 'sparse_categorical_crossentropy'

# Logging and summaries 
eval_steps: 1
keep_checkpoint_max: 3
log_frequency: 20
save_checkpoints_steps: 20
save_summary_steps: 20
start_delay_secs: 10