# Online Dataset
compressed_data_name: 'images.tar'
compressed_list_name: 'lists.tar'
url_dataset: 'http://vision.stanford.edu/aditya86/ImageNetDogs/images.tar'
url_list: 'http://vision.stanford.edu/aditya86/ImageNetDogs/lists.tar'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_images: 'Images'
data_dir_list: 'List'
label_id_json: 'labels.json'
model_dir: 'checkpoints'
images_to_predict: 'images_to_predict'

# Data files
test_data: 'test.txt'
test_mat_file: 'test_list.mat'
training_data: 'training.txt'
train_mat_file: 'train_list.mat'
validation_data: 'validation.txt'

# Data configuration
image_shape: [224, 224, 3]
shuffle: True

# Parameters that may affect training
batch_size: 10
class_mode: 'other'
depth_multiplier: 1
dropout_rate: 0.5
learning_rate: 0.001
loss: 'sparse_categorical_crossentropy'
max_steps: 50000
num_classes: 50
num_epochs: 125
regularization_rate: 0.001
tiny_model: True
width_multiplier: 1

# Logging and summaries 
eval_steps: 1
keep_checkpoint_max: 3
log_frequency: 20
save_checkpoints_steps: 20
save_summary_steps: 20
start_delay_secs: 10